### ISSUE TITLE
Add additional end points get_promoted get_listen_now get_situations

### ISSUE THREAD

**Issue by jdwoody** [gmusicproxy/gmusicproxy#119]
Add endpoints to support GMusic promoted, listen now, and situations lists.

**Comment by jdwoody** [comment]
@jeffmhubbard Is this correct?
https://github.com/M0Rf30/gmusicproxy/blob/master/GMusicProxy#L735
if there's no "id" param the delete call may try to delete a null stationId or something that was already deleted.

**Comment by jeffmhubbard** [comment]
It's definitely under-indented and could be written better. Situation stations should be transient by deault (or always) or else you get a lot of clutter in recent stations.

**Comment by jeffmhubbard** [comment]
I was trying to do some things in the wrong places it seems. I just pushed a [fix-situations](https://github.com/jeffmhubbard/gmusicproxy/tree/fix-situations) branch on my repo that should work correctly.

**Comment by jdwoody** [comment]
Should this be transient as well?
https://github.com/jeffmhubbard/gmusicproxy/blob/fix-situations/GMusicProxy#L769

**Comment by jeffmhubbard** [comment]
I've only been able to look at this briefly, but so far `_get_promoted` and `_get_situations` are working fine.  However, we should be using `api.get_top_songs` since `get_promoted_songs` was recently deprecated as well. And `_get_listen_now` is partially working.

`type=album` seems to work. I get the same results from #119 as I do from my fork. `type=artist` does not return the same results at all. In my fork, I get a list of "recommended artist" stations. With #119 I seem to be getting another list of albums. I put up a gist that shows the results I'm getting: https://gist.github.com/jeffmhubbard/8956b7c47d0fdfc8b281be46c763a26a

I do not readily see what the issue is. I'm a pretty inexperienced programmer, so I'm having trouble following some of the recent changes.

**Comment by jdwoody** [comment]
thanks for the detailed feedback. I pushed a fix a moment ago including the change to top songs. I'll probably rename the endpoint from `get_promoted` to `get_top_songs` for clarity. Let me know if you find any other issues.

**Comment by jeffmhubbard** [comment]
The last commit fixed the issue with `type=artist`. Everything seems to be returning expected results now.
